services:

  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
    networks:
      qsmith-network:
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped

  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

  qsmith:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: qsmith
    container_name: qsmith
    working_dir: /app
    volumes:
      - ./src:/app
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8082:8082"
    networks:
      - qsmith-network
    environment:
      - PYTHONPATH=/app

networks:
  qsmith-network:
