networks:
  net:
    name: qsmith-network

services:

  appsmith:
    image: index.docker.io/appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped

  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    networks:
      - net
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

  qsmith:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: qsmith
    container_name: qsmith
    working_dir: /app
    volumes:
      - ./src:/app
      - ./data:/app/data
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8082:8082"
    networks:
      - net
    environment:
      - PYTHONPATH=/app
