services:
  elasticmq:
    image: softwaremill/elasticmq-native
    container_name: elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - ./elasticmq.conf:/opt/elasticmq.conf

  queue-tester:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: queue-tester
    container_name: queue-tester
    working_dir: /app
    volumes:
      - ./src:/app
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8082:8082"
    networks:
      - wildflyNet
    environment:
      - PYTHONPATH=/app

networks:
  wildflyNet:
    external: true
